// <auto-generated />
using System;
using BusinessLicensing_Practice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessLicensing.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessLicensing_Practice.Models.AiSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ApplicationSummariesEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("DocumentValidationEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("AiSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationSummariesEnabled = false,
                            DocumentValidationEnabled = false
                        });
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationFormFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationFormFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecisionDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text");

                    b.Property<string>("EntertainmentActivityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FoodHandlingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastResubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Municipality")
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBusinessAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBusinessAddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBusinessAddressLine2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBusinessCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBusinessPostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBusinessSuburb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PopiaConsentAccepted")
                        .HasColumnType("boolean");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RevisionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UploadedDocumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UploadedDocumentPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationAiSummary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GeneratedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("ApplicationAiSummaries");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ActorDisplayName");

                    b.HasIndex("ApplicationNumber");

                    b.HasIndex("EventType");

                    b.HasIndex("Municipality");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("ApplicationAuditLogs");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantAddress")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantAddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantAddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantCity")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantEmail")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantFirstName")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantLastName")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantName")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantSuburb")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantTelephone")
                        .HasColumnType("text");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("ApplicationType")
                        .HasColumnType("text");

                    b.Property<string>("BusinessEmail")
                        .HasColumnType("text");

                    b.Property<string>("BusinessTelephone")
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<bool?>("DeclarationAccepted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeclarationAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErfNumber")
                        .HasColumnType("text");

                    b.Property<string>("LicenceSpecificDetailsJson")
                        .HasColumnType("text");

                    b.Property<bool?>("OpenOnPublicHolidays")
                        .HasColumnType("boolean");

                    b.Property<string>("PostalAddress")
                        .HasColumnType("text");

                    b.Property<string>("PostalAddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("PostalAddressLine2")
                        .HasColumnType("text");

                    b.Property<bool?>("PostalAddressSameAsBusiness")
                        .HasColumnType("boolean");

                    b.Property<string>("PostalCity")
                        .HasColumnType("text");

                    b.Property<string>("PostalPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("PostalSuburb")
                        .HasColumnType("text");

                    b.Property<string>("TradingHours")
                        .HasColumnType("text");

                    b.Property<string>("Zoning")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("ApplicationDetails");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationDocuments");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastSavedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceApplicationId")
                        .IsUnique()
                        .HasFilter("\"SourceApplicationId\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"SourceApplicationId\" IS NULL");

                    b.ToTable("ApplicationDrafts");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationDraftDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiValidationStatus")
                        .HasColumnType("text");

                    b.Property<int>("ApplicationDraftId")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDraftId", "DocumentType")
                        .IsUnique();

                    b.ToTable("ApplicationDraftDocuments");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Municipality")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.MunicipalMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("General");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenderId")
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("ApplicationId", "ReadAtUtc");

                    b.ToTable("MunicipalMessages");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RoutingName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RoutingName")
                        .IsUnique();

                    b.ToTable("Municipalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Bergrivier Municipality",
                            RoutingName = "Bergrivier Municipality"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Cederberg Municipality",
                            RoutingName = "Cederberg Municipality"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Hessequa Municipality",
                            RoutingName = "Hessequa Municipality"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Swartland Municipality",
                            RoutingName = "Swartland Municipality"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Witzenberg Municipality",
                            RoutingName = "Witzenberg Municipality"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.Application", b =>
                {
                    b.HasOne("BusinessLicensing_Practice.Models.ApplicationUser", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationAiSummary", b =>
                {
                    b.HasOne("BusinessLicensing_Practice.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationDetails", b =>
                {
                    b.HasOne("BusinessLicensing_Practice.Models.Application", "Application")
                        .WithOne("Details")
                        .HasForeignKey("BusinessLicensing_Practice.Models.ApplicationDetails", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationDocument", b =>
                {
                    b.HasOne("BusinessLicensing_Practice.Models.Application", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationDraft", b =>
                {
                    b.HasOne("BusinessLicensing_Practice.Models.Application", "SourceApplication")
                        .WithMany()
                        .HasForeignKey("SourceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BusinessLicensing_Practice.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceApplication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationDraftDocument", b =>
                {
                    b.HasOne("BusinessLicensing_Practice.Models.ApplicationDraft", "ApplicationDraft")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationDraft");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.MunicipalMessage", b =>
                {
                    b.HasOne("BusinessLicensing_Practice.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLicensing_Practice.Models.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Application");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BusinessLicensing_Practice.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BusinessLicensing_Practice.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLicensing_Practice.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BusinessLicensing_Practice.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.Application", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationDraft", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("BusinessLicensing_Practice.Models.ApplicationUser", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
